# Generated by Django 5.1.4 on 2025-01-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascension', '0003_learninggoal_current_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningplan',
            name='completed',
        ),
    ]
