# Generated by Django 5.1.4 on 2025-01-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascension', '0004_remove_learningplan_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningplan',
            old_name='lerning_goal',
            new_name='learning_goal',
        ),
    ]
