# Generated by Django 5.1.4 on 2025-01-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascension', '0005_rename_lerning_goal_learningplan_learning_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
