# Generated by Django 5.1.4 on 2025-01-17 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('ascension', '0004_remove_learningplan_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('not_started', '未完了'), ('in_progress', '進行中'), ('completed', '完了')], default='not_started', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'learning_plan')},
        ),
    ]
