# Generated by Django 5.1.4 on 2025-01-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_progress_learning_goal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set(),
        ),
    ]
